---
version: '2.1'
services:
  mysql:
    image: mysql:5.6.33
    container_name: local-mysql
    hostname: mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: test
    volumes:
      - "./local_mysql/storage:/var/lib/mysql"
      - "./local_mysql/etc/mysql:/etc/mysql"
    ports:
      - "3306:3306"
